name: Store repo behind Arup VPN

on:
  push:
    branches: [ "master" ]
    
env:
  PROJECT_NAME: 'PLACEHOLDER(PLEASE CHANGE)'

jobs:
  pack:
    runs-on: ubuntu-latest
    outputs:
      packageVersion: ${{ steps.version-extract.outputs.version }}
    steps:     
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # This ensures we get full git history
          
      - name: Get version from git
        id: version-extract
        run: |
          # Option 1: Use latest tag
          VERSION=$(git describe --tags --always)
          # Option 2: Use latest tag with fallback format
          # VERSION=$(git describe --tags --always --dirty=-d)
          # Option 3: Use short commit hash if no tags
          # VERSION=$(git rev-parse --short HEAD)
          # Option 4: Set version manually
          # VERSION="0.0.1"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT          
          
      - name: upload to GitHub workflow
        uses: actions/upload-artifact@v4  # Updated to v4 to match download version
        with:
          name: package
          path: .git
          retention-days: 1
          if-no-files-found: error  # Changed to error to catch issues early
          include-hidden-files: true  # Added to ensure .git is included
        
  distribute:
    runs-on: [self-hosted, linux, packages]
    needs: [pack]
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Distribute behind VPN
        uses: arup-group/actions-composite-arup/generic/distribute-repo@main
        with:
          project-name: ${{ env.PROJECT_NAME }}
          package-version: ${{ needs.pack.outputs.packageVersion }}
