name: Store python packages behind Arup VPN

on:
  push:
    branches: [ $default-branch ]
    
env:
  PROJECT_NAME: 'PLACEHOLDER(PLEASE CHANGE)'

jobs:
  pack:
    runs-on: ubuntu-latest
    outputs:
      packageVersion: ${{ steps.version-extract.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      
      # Change this logic if you don't have a setup.py file.
      - name: Get version number
        id: version-extract
        run: |
          version=$(python setup.py --version)
          echo "version=$version" >> $GITHUB_OUTPUT
        
      - id: package
        name: Package this repo
        uses: arup-group/actions-composite-arup/python/archive-repo@main
        with:
          project-name: ${{ env.PROJECT_NAME }}
          package-version: ${{ steps.version-extract.outputs.version }}
        
  distribute:
    runs-on: [self-hosted, linux, packages]
    needs: [pack]
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Distribute behind VPN
        uses: arup-group/actions-composite-arup/python/distribute-package@main
        with:
          project-name: ${{ env.PROJECT_NAME }}
          package-version: ${{ needs.pack.outputs.packageVersion }}
